### ISSUE TITLE
Stop deprecation of pre-connected DB object

### ISSUE THREAD

**Issue by ctrlsam** [winstonjs/winston-mongodb#194]
`winston-mongodb: preconnected object support is deprecated and will be removed in v5`

Using a preconnected DB object is useful when you're already using MongoDB in your program.
I've searched around and cannot find a reason for this feature to be deprecated, `nodejs` is now far past v5 too.

If there is a reason to keep this deprecation, I'd like to know why, and otherwise the warning _should_ be removed.

**Comment by waynehaffenden** [comment]
+1

**Comment by wbt** [comment]
The appearance of the warning indicates use of a deprecated function; is this request to just remove the warning as stated or to remove the deprecation? 

For history, the warning was added in [this commit](https://github.com/winstonjs/winston-mongodb/commit/536a622534f531d06811a3791d717175478721a0) by @yurijmikhalevich on Mar 13, 2019, nominally to fix an [issue](https://github.com/winstonjs/winston-mongodb/issues/130) around incompatibility with an updated MongoDB driver.  

I'm not an expert in this topic but am adding a response assignment to someone who knows more on this topic than I; please feel free to decline if need be!

**Comment by ContraHacker** [comment]
We're missing key info here. Like @ctrlsam asked, why is it being deprecated? Also, what is the now-recommended way of creating and connecting to a MongoDB transporter?

**Comment by hampusolsen** [comment]
Will using a connection string not needlessly establish a new connection?

Passing a db object seems to work just fine with versions below.

```
MongoDB 5.0.12
winston 3.3.5
winston-mongodb 5.0.7
```

**Comment by ctrlsam** [comment]
The benefit I can see with using a pre-connected object is that it prevents opening another connection to the DB if the pre-connected instance is already in use. It works fine, however there is a warning generated.

**Comment by zhifeng-heng** [comment]
I am also facing an issue whereby too many mongodb connection is being created after upgrading to v5 and using the mongodb connection URI. Previously on older version i was using a pre-connected mongodb connection obj and this did not happen.

Can i get some advise on how should i do this instead? Or i probably will need to downgrade to use v4 instead. Thanks!

**Comment by zhifeng-heng** [comment]
Just to provide an update.

I have created a brand new nodejs project from scratch using the latest versions (listed below) and i am still getting an error "unhandledRejection TypeError: client.db is not a function" when i use a pre-connected mongodb client obj.

**Versions:**
NodeJS - 18.7
MongoDB - 4.11.0
Winston - 3.8.2
Winston-Mongodb - 5.1.0

This is my code snippets.

`const winston = require('winston');
const { MongoClient } = require('mongodb');
require('winston-mongodb');

const MongoDbLogClient = async () => {
    const mongoClient = await MongoClient.connect('mongodb://localhost:27017/logs');
    const mongodb = await mongoClient.db();
    return mongodb;
};
const mongodb = MongoDbLogClient();

const logger = winston.createLogger({
    transports: [
        // MongoDB transport
        new winston.transports.MongoDB({
            level: 'info',
            db: mongodb,
            collection: 'server_logs'
        })]
});

logger.info('Info log');`
